# Generated by Django 4.2.16 on 2026-07-23 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('low_moisture', 'Low soil moisture'), ('disease_risk', 'Disease risk'), ('weather', 'Weather'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='alerts_aler_user_id_d01ece_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['low_moisture', 'disease_risk', 'weather', 'system'])), name='alert_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(check=models.Q(('severity__in', ['info', 'warning', 'critical'])), name='alert_severity_valid'),
        ),
    ]
