# Generated by Django 4.2.16 on 2026-07-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('irrigation', 'Irrigation'), ('fertilizer', 'Fertilizer'), ('yield', 'Yield')], max_length=20)),
                ('decision', models.CharField(max_length=120)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='farms.field')),
            ],
            options={
                'db_table': 'recommendations_recommendation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['field', 'type', '-created_at'], name='recommendat_field_i_f586d1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['irrigation', 'fertilizer', 'yield'])), name='recommendation_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.CheckConstraint(check=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='recommendation_confidence_range'),
        ),
    ]
