# Generated by Django 4.2.16 on 2026-07-23 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('base_temp', models.DecimalField(decimal_places=2, default=10.0, help_text='Base temperature (°C) for GDD accumulation.', max_digits=5)),
                ('season', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'db_table': 'farms_crop',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, default='', max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area_hectares', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farms_farm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('growth_stage', models.CharField(choices=[('germination', 'Germination'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('maturity', 'Maturity'), ('harvest', 'Harvest')], default='vegetative', max_length=20)),
                ('area_hectares', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='farms.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.farm')),
            ],
            options={
                'db_table': 'farms_field',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('battery', models.PositiveSmallIntegerField(default=100)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_nodes', to='farms.field')),
            ],
            options={
                'db_table': 'farms_sensor_node',
                'ordering': ['device_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sensornode',
            constraint=models.CheckConstraint(check=models.Q(('battery__gte', 0), ('battery__lte', 100)), name='node_battery_range'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(check=models.Q(('area_hectares__gte', 0)), name='field_area_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='farm',
            constraint=models.CheckConstraint(check=models.Q(('area_hectares__gte', 0)), name='farm_area_non_negative'),
        ),
    ]
