# Generated by Django 4.2.16 on 2026-09-22 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensornode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='dry_level',
            field=models.PositiveSmallIntegerField(default=40, help_text='Soil moisture %% below which the pump turns on.'),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='hardware_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='pump_mode',
            field=models.CharField(choices=[('auto', 'Auto (device decides from soil moisture)'), ('manual', 'Manual (farmer overrides)')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='pump_on',
            field=models.BooleanField(blank=True, help_text="Manual-mode target state. Null means 'let the device decide'.", null=True),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='pump_state',
            field=models.BooleanField(default=False, help_text='Last pump state the device reported.'),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='wet_level',
            field=models.PositiveSmallIntegerField(default=65, help_text='Soil moisture %% above which the pump turns off.'),
        ),
        migrations.AlterField(
            model_name='sensornode',
            name='field',
            field=models.ForeignKey(blank=True, help_text='Null while the device is discovered but not yet claimed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_nodes', to='farms.field'),
        ),
        migrations.AddConstraint(
            model_name='sensornode',
            constraint=models.CheckConstraint(check=models.Q(('dry_level__lt', models.F('wet_level'))), name='node_dry_below_wet'),
        ),
    ]
