# Generated by Django 4.2.16 on 2026-07-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases/%Y/%m/')),
                ('disease', models.CharField(max_length=120)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_healthy', models.BooleanField(default=False)),
                ('treatment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_reports', to='farms.field')),
            ],
            options={
                'db_table': 'diseases_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['field', '-created_at'], name='diseases_re_field_i_6831e2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='diseasereport',
            constraint=models.CheckConstraint(check=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='disease_confidence_range'),
        ),
    ]
