# Generated by Django 4.2.16 on 2026-07-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField(help_text='Volumetric water content (%).')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='farms.sensornode')),
            ],
            options={
                'db_table': 'sensors_reading',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['sensor_node', '-recorded_at'], name='reading_node_time_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sensorreading',
            constraint=models.UniqueConstraint(fields=('sensor_node', 'recorded_at'), name='reading_node_time_unique'),
        ),
        migrations.AddConstraint(
            model_name='sensorreading',
            constraint=models.CheckConstraint(check=models.Q(('soil_moisture__gte', 0), ('soil_moisture__lte', 100)), name='reading_soil_moisture_range'),
        ),
    ]
