# Generated by Django 4.2.16 on 2026-09-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='ec',
            field=models.FloatField(blank=True, help_text='Electrical conductivity (mS/cm).', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='nitrogen',
            field=models.FloatField(blank=True, help_text='N (mg/kg).', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='ph',
            field=models.FloatField(blank=True, help_text='Soil pH (0-14).', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='phosphorus',
            field=models.FloatField(blank=True, help_text='P (mg/kg).', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='potassium',
            field=models.FloatField(blank=True, help_text='K (mg/kg).', null=True),
        ),
    ]
