# Generated by Django 4.2.16 on 2026-08-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('level', models.CharField(choices=[('country', 'Country'), ('province', 'Province'), ('district', 'District'), ('sector', 'Sector')], max_length=20)),
                ('code', models.CharField(blank=True, default='', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.location')),
            ],
            options={
                'db_table': 'locations_location',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['level', 'parent'], name='locations_l_level_a9417b_idx'), models.Index(fields=['name'], name='locations_l_name_0dcc82_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(('level__in', ['country', 'province', 'district', 'sector'])), name='location_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('parent', 'name', 'level'), name='location_unique_child'),
        ),
    ]
