# Generated by Django 4.2.16 on 2026-07-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('temperature_min', models.FloatField(blank=True, null=True)),
                ('temperature_max', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('rainfall_mm', models.FloatField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='farms.farm')),
            ],
            options={
                'db_table': 'weather_record',
                'ordering': ['forecast_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='weatherrecord',
            constraint=models.UniqueConstraint(fields=('farm', 'forecast_date'), name='weather_farm_date_unique'),
        ),
    ]
